const touchControlsText = [
  "Move",
  "  Touch movement on left side of screen",
  "Move Camera",
  "  Touch movement on right side of screen",
  "shoot Arrow",
  "  Target button (hold -> release)",
  "shoot Grapple",
  "  rope button (hold -> release)",
  "Jump",
  "  up arrow on bottom-right of screen"
]

const mouseKeyboardControlsText = [
  "move",
  "  WASD keys",
  "move camera",
  "  mouse",
  "shoot arrow",
  "  Left click (hold -> release)",
  "shoot grapple",
  "  Right click (hold -> release)",
  "jump",
  "  space",
  "sprint",
  "  Shift"
]

const adjectives = [
  "Hairless",
  "Soggy",
  "Derpy",
  "Abnormal",
  "Slimy",
  "Naked",
  "Shakey",
  "Filthy",
  "Drunk",
  "Thicc",
  "Wet",
  "Sticky",
  "Dank",
  "Slick",
  "Skippy",
  "Oily",
  "Water-logged",
  "Nakey",
  "Wooden",
  "Janky",
  "Stanky",
  "Salty",
  "Sweet",
  "Sparkly",
  "Spanky",
  "Meaty",
  "Girthy",
  "Plump",
  "Ouchy",
  "Screaming",
  "Flaming",
  "Grubby",
  "Juicy",
  "Stiff",
  "Erect",
  "Emotional",
  "Fancy",
  "Pink",
  "Shaky",
  "Baby"
]

const nouns = [
  "Slingshot",
  "Dingaloid",
  "Moustache",
  "Hobo",
  "Scholar",
  "Meatball",
  "Stump",
  "Hairball",
  "Duster",
  "Bag",
  "Bucket",
  "Trap",
  "Cowboy",
  "Bazooka",
  "Shooter",
  "Snake",
  "Goat",
  "Bunny",
  "Platypus",
  "Stank",
  "Queen",
  "Bean",
  "Machine",
  "Meercat",
  "Bee",
  "Samurai",
  "Believer",
  "Gangster",
  "Slinger",
  "Shot",
  "Goon",
  "Goober",
  "Gubbler",
  "Grub",
  "Bard",
  "Pistol",
  "Baby",
  "Fiasco"
]

const cyan = 0x0974A5

const sunLightColor = 0xfff6e0

export {touchControlsText, mouseKeyboardControlsText, cyan, sunLightColor, adjectives, nouns}